# Generated by Django 5.1 on 2024-09-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="is_shareable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="resume",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="resume.header"
            ),
        ),
    ]
