# Generated by Django 5.1 on 2024-09-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_award_resume_alter_certificate_resume_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="award",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="certificate",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="educationexp",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="interest",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="link",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="personalinfo",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="professionalexp",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="resume",
            new_name="header",
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="resume",
            new_name="header",
        ),
    ]
