# Generated by Django 5.1 on 2024-09-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True),
        ),
    ]
